name: Sync GEE Repository
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'          
      - name: dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install jsbeautifier
      - name: gee auth cookie and sync       
        run: |
          eval 'set +o history' 2>/dev/null || setopt HIST_IGNORE_SPACE 2>/dev/null
           touch ~/.gitcookies
           chmod 0600 ~/.gitcookies

           git config --global http.cookiefile ~/.gitcookies

           tr , \\t <<\__END__ >>~/.gitcookies
          ${GIT_GEE_COOKIE}
          __END__
          eval 'set -o history' 2>/dev/null || unsetopt HIST_IGNORE_SPACE 2>/dev/null
          today=$(date +"%Y-%m-%d %H:%M:%S")
          mkdir gee-repo
          cd gee-repo
          git clone https://earthengine.googlesource.com/users/dmlmont/spectral
          cp ./spectral/spectral-indices.js /spectral/spectral-indices.js
          cd spectral
          git add .
          git commit -m "Sync GEE Repo with GH ${today} UTC"
          git push origin master
        env:
          GIT_GEE_COOKIE: ${{ secrets.GIT_GEE_COOKIE }}          