name: Awesome Spectral Indices
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'          
      - name: dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install jsbeautifier
      - name: execute ASI     
        run: |
          python ./.github/scripts/update_spectral_indices.py
      - name: execute Offset Scale     
        run: |
          python ./.github/scripts/update_scale_offset.py
      - name: execute Bands Constants    
        run: |
          python ./.github/scripts/update_bands_constants.py
      - name: commit
        continue-on-error: true
        run: |
          today=$(date +"%Y-%m-%d %H:%M:%S")
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Updated ASI, Offset, Scale ${today} UTC" -a
      - name: push
        continue-on-error: true
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
